### ISSUE TITLE
Android v2.0.0 does not compile correctly

### ISSUE THREAD

**Issue by dhcustom** [softgravity/titanium_flurry#11]
Generates error when compiling

UNEXPECTED TOP-LEVEL EXCEPTION:
java.lang.IllegalArgumentException: already added: Lorg/apache/http/entity/mime/content/StringBody

**Comment by dhcustom** [comment]
https://jira.appcelerator.org/browse/TC-2210, star this if anyone wants to help raise awareness to the appcelerator team and help get this fixed so we can get crash logs and stack traces.

**Comment by jdwfly** [comment]
Wow, just sad to read that bug report... came across this issue as well and will try to use the 3.1 version of flurry instead.

**Comment by dhcustom** [comment]
Yeah, it is quite sad.
You can use https://github.com/softgravity/titanium_flurry/blob/master/android/dist/sg.flurry-android-1.3.zip which is built with 3.0.5. There isn't anything extra in the analytics side until 3.2.0. Ads side there are updates but not supported by this module anyways so not important.

**Comment by dhcustom** [comment]
To fix it, manually go into FlurryAgent.jar and remove the org/apache libaries.

1, Use "jar xf" to unpack jar file.
2. Remove the org/apche directory.
3. Repackage jar cvf FlurryAgent.jar *

sg flurry v2.0.0 has bee updated with this fix.

**Comment by cbrunnkvist** [comment]
Thanks for documenting this. I could reduce it down to be able to conclude that it was the Flurry module that caused this error for me. I'm not sure though whether this ticket should be closed or remain opened (until it is resolved either in Titanium or by a permanent workaround here) because I nearly missed it when browsing.

**Comment by dhcustom** [comment]
Please see the above comment. I have fixed the module and will now compile and work as expected.
Download the latest modules file in the "dist" directory and it will work :)
