### ISSUE TITLE
Module causes apps to crash on x86 Android

### ISSUE THREAD

**Issue by davidfischer** [softgravity/titanium_flurry#13]
Apps including sg.flurry do not run on x86 devices. Thus far, I have only tested on the Android emulator. The emulator runs fine using ARM. Wrapping `require('sg.flurry')` in a try/catch block fails to catch the exception. Currently, my workaround is to only include the module in production builds and not in dev/test builds. When I do that, I can catch the exception that `require` raises correctly.

`E/TiApplication( 3336): java.lang.UnsatisfiedLinkError: Couldn't load sg.flurry from loader dalvik.system.PathClassLoader`

**Comment by thisishuey** [comment]
Having same error. Easiest way to recreate is using the GenyMotion emulator.

And here is the error I'm seeing in the console:

[WARN] :   The module sg.flurry does not support the ABI: x86
[WARN] :   It only supports the following ABIs: armeabi, armeabi-v7a
[WARN] :   Your application will most likely encounter issues

**Comment by vatsalengg** [comment]
Just compile these sg.flurry's source using at least minimum Titanium sdk: 3.0.2.GA. This will add x86 based library as 'x86' folder in its libs folder. Which will resolve issue of that error.

**Comment by thisishuey** [comment]
That worked perfect for me. Thanks @vatsalengg!

**Comment by davidfischer** [comment]
This works for me as well. Thanks @vatsalengg.
