### ISSUE TITLE
Update Flurry SDK to 3.0.7

### ISSUE THREAD

**Issue by jonatansberg** [softgravity/titanium_flurry#7]
A new SDK release is out. 

Release Notes:
- Fix for referencing deallocated Ad delegate in Clips
- Reduce possible duplicate symbols between Analytics lib and Ad libs whencompiling with -all_load option
- Fix for the issue where at times the Reengagement banner expands from the top even though the collapsed banner is at the bottom of the screen
- Update Reengagement documentation

**Comment by dhcustom** [comment]
upgraded to 3.0.7. Let me know how it goes.

**Comment by jonatansberg** [comment]
You've already updated to 3.0.8. Closing this.
