### ISSUE TITLE
AppCircles?

### ISSUE THREAD

**Issue by trkfabi** [softgravity/titanium_flurry#8]
Is there a way to integrate Flurry AppCircles into the module?

**Comment by dhcustom** [comment]
I would suggest not adding app circles to this module to keep it small.
However, it should be simple to create a separate module for app circles using this code as a base as well as reading the titanium module guides.
App circle seems to have much less APIs so should be even easier to implement.
http://support.flurry.com/sdkdocs/iOS/interface_flurry_app_circle.html
